# Generated by Django 3.1.2 on 2020-10-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.CharField(blank=True, max_length=250)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
